name: 🐞 Bug / Problema na IDE
description: Reportar problemas encontrados na interface ou na execução de código
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Agradecemos por dedicar um tempo para reportar um problema na IDE. Para nos ajudar a entender e corrigir o problema, por favor, preencha o formulário abaixo com o máximo de detalhes possível.

        Não se esqueça de incluir o título acima para descrever o problema de forma resumida.

        ---
  - type: textarea
    id: description
    attributes:
      label: Descrição do problema
      description: Explique brevemente o problema encontrado.
      placeholder: |
        Exemplo: Ao tentar executar o código, a IDE exibe um erro de sintaxe ao usar a função "escreva".
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Código
      description: Por favor, cole abaixo o código que está causando o problema.
      render: portugol
      placeholder: |
        programa {
          funcao inicio() {
            // Seu código aqui
          }
        }
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Comentários adicionais
      description: |
        Informações adicionais que possam ajudar a entender o problema. Exemplos: passos para reproduzir o erro, mensagens de erro, etc.

        Dica: Você pode anexar imagens ou arquivos de log clicando nesta área para destacá-la e, em seguida, arrastando os arquivos para cá.
    validations:
      required: false
